### PR TITLE
Create AWS-S3-Dask-XGBoost.ipynb

### PR DESCRIPTION
**Pull request by zhonghua-zheng**
Dear all,

Inspired by the availability of the CESM large ensemble on AWS S3, I developed this workflow to show how to use **dask-xgboost** to deal with the data from S3.

The example here shows how to predict    
**"TREFHTMX": Maximum reference height temperature over output period**
using features:   
**"PRECT": Total (convective and large-scale) precipitation rate (liq + ice)**     
**"WSPDSRFAV": Horizontal total wind speed average at the surface**  
**"TS": Surface temperature (radiative)**  
**"TREFHT": Reference height temperature**    
Please feel free to let me know if you have any questions and suggestions!

Best,
Zhonghua

### CODE REVIEW

**Comment by djgagne** [comment]
It looks really promising as a workflow example. Would it be possible for you to add a bit more text description of each step and explain the variables and task more in the notebook?

**Comment by zhonghua-zheng** [comment]
> It looks really promising as a workflow example. Would it be possible for you to add a bit more text description of each step and explain the variables and task more in the notebook?

@djgagne Hi David, Thank you very much for your suggestions! I just improved my workflow with a detailed description!

**Comment by rabernat** [comment]
Thanks so much for your contribution here! I'm happy to merge it.

Going forward, we should think about how to make these examples runnable via binder.

**Comment by zhonghua-zheng** [comment]
> Thanks so much for your contribution here! I'm happy to merge it.
> 
> Going forward, we should think about how to make these examples runnable via binder.

@rabernat Hi Ryan, thank you very much for your help! Yes, we should make this example runnable via binder.

**Pull request merged**
